TILE_WIDTH = 15
TILE_COLOR = (0, 0, 0)
TILE_SPACING = 2

FOOD_COLOR = (255, 0, 0, 255)

SNAKE_SPEED = 100

WINDOW_RATIO = 1
NUMBER_OF_TILES_HEIGHT = 20
WINDOW_HEIGHT = (
    NUMBER_OF_TILES_HEIGHT * TILE_WIDTH + (NUMBER_OF_TILES_HEIGHT - 1) * TILE_SPACING
)
NUMBER_OF_TILES_WIDTH = NUMBER_OF_TILES_HEIGHT * WINDOW_RATIO
WINDOW_WIDTH = (
    NUMBER_OF_TILES_WIDTH * TILE_WIDTH
    + (WINDOW_RATIO * NUMBER_OF_TILES_HEIGHT - 1) * TILE_SPACING
)
